runtime: go
api_version: go1.9

handlers:
    - url: /api*
      secure: always
      login: required
      script: _go_app

    - url: /public
      secure: always
      login: required
      static_dir: public

    - url: /
      secure: always
      login: required
      static_files: index.html
      upload: index\.html
